### PR TITLE
It seems like a duplicate module.export?

### PR DESCRIPTION
**Pull request by think2011**

### CODE REVIEW

**Comment by bripkens** [comment]
Actually, the code is intended to keep the references of `exports` and `module.exports` consistent. This is a Node.js best practice. For this reason, I am going to close this pull request.

Thank you for wanting to help out! :)

**Comment by think2011** [comment]
qq20160105-0

Because webstorm reminds me ↑, could you give me more detail about this? thanks 

sorry for my low english :-)

**Comment by bripkens** [comment]
That seems to an issue with your IDE configuration. Check out the Node.js documentation for more information:

https://nodejs.org/api/globals.html#globals_exports

**Comment by think2011** [comment]
thanks ;-)

**Pull request closed without merging**
